# Generated by Django 2.0.7 on 2021-10-19 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('accountnumber', models.CharField(db_column='accountNumber', max_length=50, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=19)),
                ('dateopened', models.DateField(db_column='dateOpened')),
                ('lastupdated', models.DateField(db_column='lastUpdated')),
            ],
            options={
                'db_table': 'accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40)),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'account_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=10)),
            ],
            options={
                'db_table': 'bank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('ssn', models.CharField(db_column='SSN', max_length=11, unique=True)),
                ('dateofbirth', models.DateField(db_column='dateOfBirth')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=10)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCards',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('cvc', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'credit_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CreditCardTypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('min_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'credit_card_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebitCards',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('cvc', models.CharField(max_length=3)),
                ('expiry_date', models.DateField()),
            ],
            options={
                'db_table': 'debit_cards',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DebitCardTypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'debit_card_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('ssn', models.CharField(max_length=45)),
                ('dateofbirth', models.DateField(db_column='dateOfBirth')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=25)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=19)),
                ('position', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date', models.DateField()),
                ('period', models.IntegerField()),
            ],
            options={
                'db_table': 'loans',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoanTypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
            options={
                'db_table': 'loan_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=10)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionTypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'transaction_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccountCustomers',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='onlinebanking_app.Accounts')),
            ],
            options={
                'db_table': 'account_customers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BankEmployees',
            fields=[
                ('bankid', models.ForeignKey(db_column='BankID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='onlinebanking_app.Bank')),
            ],
            options={
                'db_table': 'bank_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.ForeignKey(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='onlinebanking_app.Clients')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
    ]
